# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wrist_classifier_pb2 as wrist__classifier__pb2


class WristMovementClassifierStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.wrist_movement_classifier = channel.unary_unary(
                '/WristMovementClassifier/wrist_movement_classifier',
                request_serializer=wrist__classifier__pb2.Measurement.SerializeToString,
                response_deserializer=wrist__classifier__pb2.Movement.FromString,
                )


class WristMovementClassifierServicer(object):
    """Define the service
    """

    def wrist_movement_classifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WristMovementClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'wrist_movement_classifier': grpc.unary_unary_rpc_method_handler(
                    servicer.wrist_movement_classifier,
                    request_deserializer=wrist__classifier__pb2.Measurement.FromString,
                    response_serializer=wrist__classifier__pb2.Movement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WristMovementClassifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WristMovementClassifier(object):
    """Define the service
    """

    @staticmethod
    def wrist_movement_classifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WristMovementClassifier/wrist_movement_classifier',
            wrist__classifier__pb2.Measurement.SerializeToString,
            wrist__classifier__pb2.Movement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
